//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class March_2023
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<decimal> C1DailiSalary { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<decimal> C2DailiSalary { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<decimal> C3DailiSalary { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<decimal> C4DailiSalary { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<decimal> C5DailiSalary { get; set; }
        public Nullable<int> C6 { get; set; }
        public Nullable<decimal> C6DailiSalary { get; set; }
        public Nullable<int> C7 { get; set; }
        public Nullable<decimal> C7DailiSalary { get; set; }
        public Nullable<int> C8 { get; set; }
        public Nullable<decimal> C8DailiSalary { get; set; }
        public Nullable<int> C9 { get; set; }
        public Nullable<decimal> C9DailiSalary { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<decimal> C10DailiSalary { get; set; }
        public Nullable<int> C11 { get; set; }
        public Nullable<decimal> C11DailiSalary { get; set; }
        public Nullable<int> C12 { get; set; }
        public Nullable<decimal> C12DailiSalary { get; set; }
        public Nullable<int> C13 { get; set; }
        public Nullable<decimal> C13DailiSalary { get; set; }
        public Nullable<int> C14 { get; set; }
        public Nullable<decimal> C14DailiSalary { get; set; }
        public Nullable<int> C15 { get; set; }
        public Nullable<decimal> C15DailiSalary { get; set; }
        public Nullable<int> C16 { get; set; }
        public Nullable<decimal> C16DailiSalary { get; set; }
        public Nullable<int> C17 { get; set; }
        public Nullable<decimal> C17DailiSalary { get; set; }
        public Nullable<int> C18 { get; set; }
        public Nullable<decimal> C18DailiSalary { get; set; }
        public Nullable<int> C19 { get; set; }
        public Nullable<decimal> C19DailiSalary { get; set; }
        public Nullable<int> C20 { get; set; }
        public Nullable<decimal> C20DailiSalary { get; set; }
        public Nullable<int> C21 { get; set; }
        public Nullable<decimal> C21DailiSalary { get; set; }
        public Nullable<int> C22 { get; set; }
        public Nullable<decimal> C22DailiSalary { get; set; }
        public Nullable<int> C23 { get; set; }
        public Nullable<decimal> C23DailiSalary { get; set; }
        public Nullable<int> C24 { get; set; }
        public Nullable<decimal> C24DailiSalary { get; set; }
        public Nullable<int> C25 { get; set; }
        public Nullable<decimal> C25DailiSalary { get; set; }
        public Nullable<int> C26 { get; set; }
        public Nullable<decimal> C26DailiSalary { get; set; }
        public Nullable<int> C27 { get; set; }
        public Nullable<decimal> C27DailiSalary { get; set; }
        public Nullable<int> C28 { get; set; }
        public Nullable<decimal> C28DailiSalary { get; set; }
        public Nullable<int> C29 { get; set; }
        public Nullable<decimal> C29DailiSalary { get; set; }
        public Nullable<int> C30 { get; set; }
        public Nullable<decimal> C30DailiSalary { get; set; }
        public Nullable<int> C31 { get; set; }
        public Nullable<decimal> C31DailiSalary { get; set; }
        public Nullable<decimal> MonthiySalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
