//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollTrackingDBEntities : DbContext
    {
        public PayrollTrackingDBEntities()
            : base("name=PayrollTrackingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<PositionsAndPay> PositionsAndPays { get; set; }
        public virtual DbSet<SalaryBonus> SalaryBonuses { get; set; }
        public virtual DbSet<April_2023> April_2023 { get; set; }
        public virtual DbSet<August_2023> August_2023 { get; set; }
        public virtual DbSet<December_2023> December_2023 { get; set; }
        public virtual DbSet<February_2023> February_2023 { get; set; }
        public virtual DbSet<January_2023> January_2023 { get; set; }
        public virtual DbSet<July_2023> July_2023 { get; set; }
        public virtual DbSet<June_2023> June_2023 { get; set; }
        public virtual DbSet<March_2023> March_2023 { get; set; }
        public virtual DbSet<May_2023> May_2023 { get; set; }
        public virtual DbSet<November_2023> November_2023 { get; set; }
        public virtual DbSet<October_2023> October_2023 { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<September_2023> September_2023 { get; set; }
    }
}
