//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id_user { get; set; }
        public string login_user { get; set; }
        public string pasword_user { get; set; }
    }
}
